title: "Read QC"

report_header_info:
  - Pipeline: "read_QC"
  - Version: "v0.0.1"
  - Help contact: "https://jira.sanger.ac.uk/servicedesk/customer/portal/16/group/57"

export_plots: true
disable_version_detection: true

#clean names
fn_clean_exts: ".prefilter"

# Run only these modules
run_modules:
  - fastqc
  - kraken

module_order:
  - fastqc:
      name: "FastQC (raw reads)"
      info: "This section of the report shows FastQC results."
      path_filters:
        - "*.zip"

  - kraken:
      name: "Kraken 2"
      info: "This section of the report shows Kraken 2 classification results."

# Kraken2 module configuration
module_settings:
  kraken:
    top_n: 5
    title: "Read QC" # Set custom title for Kraken2 reports

# Ensure Kraken2 files are properly matched
fn_glob:
  kraken: "*.tsv"
